version: 4.6.{build}

branches:
  only:
    - Extended

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}' 
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
  
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "{version}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

configuration: Release

image: Visual Studio 2019 Preview

install:
  - cmd: choco install dotnetcore-sdk --pre

before_build:
  - nuget restore DotNetProjects.Wpf.Extended.Toolkit.sln
  
build:
  project: DotNetProjects.Wpf.Extended.Toolkit.sln

test: off

artifacts:
  - path: Src\Xceed.Wpf.Toolkit\bin\Release\Xceed.Wpf.Toolkit.dll
    name: Xceed.Wpf.Toolkit.dll
  - path: Src\Xceed.Wpf.Toolkit\bin\Release\Xceed.Wpf.Toolkit.pdb
    name: Xceed.Wpf.Toolkit.pdb
  - path: '**\*.nupkg'

#uncomment to publish to NuGet
deploy:
  provider: NuGet
  api_key:
    secure: OrhpK2cLXXcoWW+hU6xAv3eeKIbATEFbenteoFsi9EfM1yyDof6ZuNKAsA3Vy6vb
  artifact: /.*\.nupkg/
  
  
